SCANJLIB-208
SonarSource/sonar-scanner-java-library pull request #165
Opened 2024-04-23 13:50 UTC by ericg138

2024-04-29 15:18 UTC, henryju reviewed
May I let you rebase your branch on top of the master branch to make the review easier for me?

2024-04-29 15:18 UTC, henryju commented on .cirrus.yml
> +#      - QA_CATEGORY: DEV
We should put this back

2024-05-02 10:30 UTC, henryju requested changes
First round of comments :)

2024-05-02 10:30 UTC, henryju commented on lib/src/main/java/org/sonarsource/scanner/lib/OldScannerEngineFacade.java
> +public class OldScannerEngineFacade extends ScannerEngineFacade {
```suggestion
public class InProcessScannerEngineFacade extends ScannerEngineFacade {
```

2024-05-02 10:30 UTC, henryju commented on lib/src/main/java/org/sonarsource/scanner/lib/ScannerEngineBootstrapper.java
> +    if (isSonarCloud) {
It might be better not to call this method if this is SonarCloud, as it doesn't make sense. Else, annotate with `@CheckForNull`

2024-05-02 10:30 UTC, henryju commented on lib/src/main/java/org/sonarsource/scanner/lib/ScannerEngineBootstrapper.java
> +      return new OldScannerEngineFacade(properties, launcher, logOutput, isSonarCloud, serverVersion);
Can't we create a third facade for simulation mode?

2024-05-02 10:30 UTC, henryju commented on lib/src/main/java/org/sonarsource/scanner/lib/ScannerEngineBootstrapper.java
> +      return serverConnection.callServerApi("/analysis/version");
Be careful, there is now 2 base Urls: one for the old API, and one for the new API. Maybe we need 2 methods on serverConnection: `callRestApi` and `callWebApi`?

2024-05-02 10:30 UTC, henryju commented on lib/src/main/java/org/sonarsource/scanner/lib/ScannerEngineBootstrapper.java
> +      return serverConnection.callServerApi("/analysis/version");
```suggestion
      return serverConnection.callRestApi("/analysis/version");
```

2024-05-02 10:30 UTC, henryju commented on lib/src/main/java/org/sonarsource/scanner/lib/ScannerEngineBootstrapper.java
> +        return serverConnection.callServerApi("/api/server/version");
```suggestion
        return serverConnection.callWebApi("/api/server/version");
```

2024-05-02 10:30 UTC, henryju commented on lib/src/main/java/org/sonarsource/scanner/lib/ScannerEngineBootstrapper.java
> +    if (!bootstrapProperties.containsKey(SCANNER_OS)) {
Why testing for the property while the method `setBootstrapPropertyIfNotAlreadySet` already does it?

2024-05-02 10:30 UTC, henryju commented on lib/src/main/java/org/sonarsource/scanner/lib/internal/BootstrapIndexDownloader.java
> +      index = conn.callServerApi("/batch/index");
```suggestion
      index = conn.callWebApi("/batch/index");
```

2024-05-02 10:30 UTC, henryju commented on lib/src/main/java/org/sonarsource/scanner/lib/internal/JarDownloader.java
> +      connection.downloadServerFile(format("/batch/file?name=%s", filename), toFile.toPath());
```suggestion
      connection.downloadFileFromWebApi(format("/batch/file?name=%s", filename), toFile.toPath());
```

2024-05-02 10:30 UTC, henryju commented on lib/src/main/java/org/sonarsource/scanner/lib/internal/JavaRunnerFactory.java
> +      logger.info(format("JRE provisioning is disabled, the java executable %s will be used.", javaExecutable));
```suggestion
      logger.info(format("JRE provisioning is disabled, the java executable '%s' will be used.", javaExecutable));
```

2024-05-02 10:30 UTC, henryju commented on lib/src/main/java/org/sonarsource/scanner/lib/internal/JavaRunnerFactory.java
> +        logger.error("Failed to get the JRE, retrying...");
```suggestion
        logger.warn("Failed to get the JRE, retrying...");
```

2024-05-02 10:30 UTC, henryju commented on lib/src/main/java/org/sonarsource/scanner/lib/internal/JavaRunnerFactory.java
> +      String response = serverConnection.callServerApi(format(API_PATH_JRE + "?os=%s&arch=%s", os, arch));
```suggestion
      String response = serverConnection.callRestApi(format(API_PATH_JRE + "?os=%s&arch=%s", urlEncode(os), urlEncode(arch)));
```

2024-05-02 10:30 UTC, henryju commented on lib/src/main/java/org/sonarsource/scanner/lib/internal/JavaRunnerFactory.java
> +        throw new IllegalStateException("No JRE metadata found for os[" + os + "] and arch[" + arch + "]");
We can log as warning, but then we should fallback to use a local JRE. This will be a way to disable the feature from server-side (always return an empty list).

2024-05-02 10:30 UTC, henryju commented on lib/src/main/java/org/sonarsource/scanner/lib/internal/JavaRunnerFactory.java
> +        connection.downloadFile(jreMetadata.getDownloadUrl(), toFile.toPath(), false);
```suggestion
        connection.downloadFromExternalUrl(jreMetadata.getDownloadUrl(), toFile.toPath(), false);
```
be sure to not pass authentication header in this case!

2024-05-02 10:30 UTC, henryju commented on lib/src/main/java/org/sonarsource/scanner/lib/internal/JavaRunnerFactory.java
> +        connection.downloadServerFile(API_PATH_JRE + "/" + jreMetadata.id, toFile.toPath());
```suggestion
        connection.downloadFileFromRestApi(API_PATH_JRE + "/" + jreMetadata.id, toFile.toPath());
```

2024-05-02 10:30 UTC, henryju commented on lib/src/main/java/org/sonarsource/scanner/lib/internal/OsResolver.java
> +    return content.stream().anyMatch(line -> line.toLowerCase(Locale.ENGLISH).contains("alpine"));
Minor concern about not using the same regexp as VSCode. I tend to think that they should have a good reason. But not sure :)

2024-05-02 10:30 UTC, henryju commented on lib/src/main/java/org/sonarsource/scanner/lib/internal/ScannerEngineLauncherFactory.java
> +        connection.downloadFile(scannerEngineMetadata.getDownloadUrl(), toFile.toPath(), false);
```suggestion
        connection.downloadFromExternalUrl(scannerEngineMetadata.getDownloadUrl(), toFile.toPath(), false);
```

2024-05-02 10:30 UTC, henryju commented on lib/src/main/java/org/sonarsource/scanner/lib/internal/ScannerEngineLauncherFactory.java
> +        connection.downloadServerFile(API_PATH_ENGINE, toFile.toPath());
```suggestion
        connection.downloadFileFromRestApi(API_PATH_ENGINE, toFile.toPath());
```

2024-05-02 10:30 UTC, henryju commented on lib/src/main/java/org/sonarsource/scanner/lib/internal/http/ServerConnection.java
> +    baseUrlWithoutTrailingSlash = removeTrailingSlash(bootstrapProperties.get(ScannerProperties.HOST_URL));
I think here is the right place to handle the new `apiBaseUrl` logic.

2024-05-02 12:08 UTC, ericg138 commented on lib/src/main/java/org/sonarsource/scanner/lib/internal/OsResolver.java
> +    return content.stream().anyMatch(line -> line.toLowerCase(Locale.ENGLISH).contains("alpine"));
I changed it, I don't use the same regex but something that does the same, let me know if I'm missing something

2024-05-02 12:36 UTC, ericg138 commented on lib/src/main/java/org/sonarsource/scanner/lib/ScannerEngineBootstrapper.java
> +    if (!bootstrapProperties.containsKey(SCANNER_OS)) {
Because I don't want to do the OS resolution if I don't need it. I will use `setBootstrapProperty` instead.

2024-05-02 12:43 UTC, ericg138 commented on lib/src/main/java/org/sonarsource/scanner/lib/internal/JavaRunnerFactory.java
> +        connection.downloadFile(jreMetadata.getDownloadUrl(), toFile.toPath(), false);
Yes there is a boolean param for that

2024-05-02 13:24 UTC, henryju approved these changes
As discussed, I think you can merge and we will continue the work in separate PRs. Well done!

2024-05-02 13:24 UTC, henryju commented on lib/src/test/java/org/sonarsource/scanner/lib/internal/http/ServerConnectionTest.java
> +  void downloadFromExternalUrl_shouldNotPassAuth(@TempDir Path tmpFolder) throws Exception {
Nicel!

2024-05-02 13:45 UTC, ericg138 commented on lib/src/main/java/org/sonarsource/scanner/lib/internal/JavaRunnerFactory.java
> +        throw new IllegalStateException("No JRE metadata found for os[" + os + "] and arch[" + arch + "]");
I created a subtask for this

2024-05-02 13:45 UTC, merged