BUILD-5727 Update Cirrus CI image used to use JDK21 LTS instead of JDK18 EOL
SonarSource/sonar-scanner-java-library pull request #191
Opened 2024-07-18 11:23 UTC by sebastienvermeille

## Changes

- [x] Update Cirrus CI image used to use JDK21 LTS instead of JDK18 EOL)
      (JDK18 will no longer be produced by ci-docker-images project as it is EOL)

2024-07-18 12:41 UTC, jayadeep-km-sonarsource approved these changes

2024-07-18 14:51 UTC, henryju requested changes

2024-07-18 14:51 UTC, henryju commented on pom.xml
> +      <dependency>
I think this is better to update Mockito than "patching" to use a more recent version of byte-buddy, while this is not a direct dependency of our project.

2024-07-18 14:56 UTC, sebastienvermeille commented on pom.xml
> +      <dependency>
HI @henryju good point, this is how I initially wanted to address the issue but neither upgrading the parent-oss version neither the mockito seemed to address the issue.

Let me try another time in a dedicated commit so we can see :+1:

2024-07-18 15:00 UTC, sebastienvermeille commented on pom.xml
> +      <dependency>
I pushed a commit to demonstrate the test with updating only Mockito: 05760a2ab7dae30a25e96d108e05f1fc4b7f63ef

2024-07-18 15:36 UTC, henryju commented on pom.xml
> +      <dependency>
I am having a look

2024-07-18 15:39 UTC, henryju commented on pom.xml
> +      <dependency>
The problem is coming from assertj, also using bytebuddy. I pushed a commit to fix the issue.

2024-07-18 16:25 UTC, henryju approved these changes
Please squash the commits before merging.

2024-07-19 08:09 UTC, sebastienvermeille commented on pom.xml
> +      <dependency>
ow nice catch!

2024-07-19 08:09 UTC, merged